// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "amplifyauth-urvi-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3g6b39ctq95b5.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:37f5c84a-f12d-4c13-9ee8-fabcdb09800b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4Cm89lye9",
    "aws_user_pools_web_client_id": "744sum3rvvu97t9cj5qeegbdde",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gsjcqca3mzgzro6ololu5wczzu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
